# Generated by Django 5.2.14 on 2026-06-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_alter_space_space_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemember',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='spaces.space'),
        ),
    ]
