# Generated by Django 5.2.14 on 2026-06-13 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_rename_space_id_spacemember_space_and_more'),
        ('stars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stars/'),
        ),
        migrations.AlterField(
            model_name='star',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='spaces.space'),
        ),
        migrations.AlterField(
            model_name='star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
