# Generated by Django 5.2.14 on 2026-06-22 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0005_rename_star_star_star_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['sequence']},
        ),
        migrations.RemoveField(
            model_name='star',
            name='star_id',
        ),
        migrations.AddField(
            model_name='star',
            name='group_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='star',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='star',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='star',
            name='x_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='star',
            name='y_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='star',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.ImageField(default=' ', upload_to='stars/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
