# Generated by Django 5.2.14 on 2026-06-22 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0006_alter_star_options_remove_star_star_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={},
        ),
        migrations.RemoveField(
            model_name='star',
            name='group_index',
        ),
        migrations.RemoveField(
            model_name='star',
            name='id',
        ),
        migrations.RemoveField(
            model_name='star',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='star',
            name='x_coord',
        ),
        migrations.RemoveField(
            model_name='star',
            name='y_coord',
        ),
        migrations.AddField(
            model_name='star',
            name='star_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='star',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stars/'),
        ),
        migrations.AlterField(
            model_name='star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
