# Generated by Django 5.2.14 on 2026-06-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0007_alter_star_options_remove_star_group_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
