# Generated by Django 5.2.14 on 2026-06-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0008_star_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='sequence',
        ),
    ]
